"""Build web/demo.html (the public demo) from lane B's app page, src/sept25_build/agent/ui/app.html.

    python3 web/build_app_demo.py

The page keeps its own ?mock=1 hook, but the mock is swapped for one that replays a real recorded run from demo.json
(lane B's /api/overview at each stage and the steps each check took; see web/export_demo.py). Order follows the
recording: add the sub-processor, then the AI-training clause, then undo. Each edit asserts its anchor exists.
"""

from pathlib import Path

WEB = Path(__file__).parent
APP = WEB.parent / "src" / "sept25_build" / "agent" / "ui" / "app.html"
SITE = "https://trust.nightswatch-inc.example"  # display only: the recorded run used a quick tunnel that is gone

MOCK = r"""function makeMock() {
  // GENERATED by web/build_app_demo.py: replays one real run (demo.json) instead of lane B's invented mock data.
  const SITE = "__SITE__";
  const rec = fetch("demo.json").then(r => { if (!r.ok) throw new Error("recording " + r.status); return r.json(); }).then(d => d.app);
  const m = {stage: null, jobs: {}, current: null, nextId: 1};
  const overview = A => m.stage ? Object.assign({}, m.stage === "base" ? A.base : A.stages[m.stage], {site_url: SITE})
                                : Object.assign({}, A.base, {site_url: SITE, watching: false, vendors: [], latest_event: null});
  const same = [["Applying the change to Tinybird's demo mirror", "Same as what Night's Watch already has"],
                ["Read Tinybird's pages via Nimble", ""], ["Result: nothing changed that affects your policies", ""]];
  function next(A, kind, sc) {
    const at = m.stage, clean = at === "base" || at === "undo";
    if (kind === "onboard") return {to: "base", plan: A.onboard};
    if (sc === "new_subprocessor" && clean) return {to: sc, plan: A.sims[sc]};
    if (sc === "training_clause" && at === "new_subprocessor") return {to: sc, plan: A.sims[sc]};
    if (sc === "undo" && !clean) return {to: "undo", plan: A.sims.undo};
    if (sc === "training_clause" && clean)
      return {error: "In this recorded run the AI-training clause changed after the new sub-processor. Run \"Tinybird adds a sub-processor\" first."};
    return {to: at, plan: same};
  }
  function startJob(A, kind, sc) {
    if (m.current && m.jobs[m.current].status === "running") return {status: 409, data: {error: "busy"}};
    const n = next(A, kind, sc);
    if (n.error) return {status: 400, data: {error: n.error}};
    const id = "rec" + m.nextId++;
    m.jobs[id] = {id, kind, t0: Date.now(), plan: n.plan, to: n.to, status: "running"};
    m.current = id;
    return {status: 200, data: {job: id}};
  }
  function jobView(id) {
    const j = m.jobs[id]; if (!j) return {status: 404, data: {error: "not found"}};
    const n = Math.floor((Date.now() - j.t0) / (reduced() ? 1 : 850));
    const steps = j.plan.slice(0, n + 1).map(([text, detail], i) => ({text, state: i < n ? "done" : "active", detail: i < n ? detail : ""}));
    if (n >= j.plan.length && j.status === "running") { j.status = "done"; m.stage = j.to; }
    return {status: 200, data: {id, kind: j.kind, status: j.status, steps, error: null}};
  }
  return async (method, path, body) => {
    const A = await rec;
    await new Promise(r => setTimeout(r, 80));
    if (path === "/api/overview") return {status: 200, data: overview(A)};
    if (path === "/api/onboard") return startJob(A, "onboard");
    if (path === "/api/simulate") return startJob(A, "simulate", body.scenario);
    const jm = path.match(/^\/api\/job\/(.+)$/); if (jm) return jobView(decodeURIComponent(jm[1]));
    return {status: 404, data: {error: "not found"}};
  };
}
"""


def build(s: str) -> str:
    def rep(old: str, new: str) -> None:
        nonlocal s
        assert s.count(old) == 1, f"anchor not found once in app.html: {old[:80]!r}"
        s = s.replace(old, new)

    rep('const MOCK = params.has("mock") && params.get("mock") !== "0";', "const MOCK = true;  // public demo: always the recording")
    a, b = s.index("function makeMock() {"), s.index("const mockApi = MOCK ? makeMock() : null;")
    s = s[:a] + MOCK.replace("__SITE__", SITE) + s[b:]
    rep('n.textContent = "mock data";',
        'n.innerHTML = \'Replay of a real recorded run · <a href="guided.html" style="color:inherit">detailed view</a>\';')
    # "About" is the landing page, which on nightswatch.app sits next to this file
    rep('<a class="about" href="/about/"', '<a class="about" href="./"')
    # a company the visitor names needs the live service (it opens that company's site): not in a recording
    rep('  {id: "custom", label: "Tinybird adds a company you choose"},\n', '')
    rep('<p class="hint">Demo company: Night\'s Watch Inc.</p>',
        '<p class="hint">Demo company: Night\'s Watch Inc. This page replays one real run on demo mirrors of its vendors\' pages.</p>')
    assert "Example Email Delivery" not in s and "fetch(path" in s
    return s


if __name__ == "__main__":
    (WEB / "demo.html").write_text(build(APP.read_text()))
    print("wrote web/demo.html from", APP.relative_to(WEB.parent))
