"""Build web/demo.html (the public demo) from lane B's app page, src/sept25_build/agent/ui/app.html.

Our demo company replays a real recorded run; any other company is checked live: the page asks the Worker
(web/contact-worker, POST /check), which runs lane B's check in GitHub Actions (web/live) and keeps results in D1.

    python3 web/build_app_demo.py

The page keeps its own ?mock=1 hook, but the mock is swapped for one that replays a real recorded run from demo.json
(lane B's /api/overview at each stage and the steps each check took; see web/export_demo.py). Order follows the
recording: add the sub-processor, then the AI-training clause, then undo. Each edit asserts its anchor exists.
"""

from pathlib import Path

WEB = Path(__file__).parent
APP = WEB.parent / "src" / "sept25_build" / "agent" / "ui" / "app.html"
SITE = "https://trust.nightswatch-inc.example"  # display only: the recorded run used a quick tunnel that is gone
LIVE = "https://nights-watch-contact.venkatsr12.workers.dev"  # live checks: web/contact-worker

MOCK = r"""function makeMock() {
  // GENERATED by web/build_app_demo.py. Our demo company replays one real recorded run (demo.json); any other
  // company is checked live (Worker -> GitHub Actions running lane B's check -> D1).
  const SITE = "__SITE__", LIVE = "__LIVE__", demoHost = new URL(SITE).hostname;
  const rec = fetch("demo.json").then(r => { if (!r.ok) throw new Error("recording " + r.status); return r.json(); }).then(d => d.app);
  const m = {stage: null, live: null, jobs: {}, current: null, nextId: 1};
  // one level only here: a vendor's own list is read by the full product, so the panel says so instead of asking
  const liveOverview = () => Object.assign({}, m.live, {watching: true, vendors: (m.live.vendors || []).map(v => Object.assign({}, v,
    {chain: "off", chain_error: "Reading each sub-processor's own list is part of the full product. This public check reads one level."}))});
  const overview = A => m.stage === "live" ? liveOverview() : m.stage ? Object.assign({}, m.stage === "base" ? A.base : A.stages[m.stage], {site_url: SITE})
                                : Object.assign({}, A.base, {site_url: SITE, watching: false, vendors: [], latest_event: null});
  const same = [["Applying the change to Tinybird's demo mirror", "Same as what Night's Watch already has"],
                ["Read Tinybird's pages via Nimble", ""], ["Result: nothing changed that affects your policies", ""]];
  function next(A, kind, sc) {
    const at = m.stage, clean = at === "base" || at === "undo";
    if (kind === "onboard") return {to: "base", plan: A.onboard};
    if (at === "live") return {error: "Simulations run on our demo company in this public demo."};
    if (sc === "new_subprocessor" && clean) return {to: sc, plan: A.sims[sc]};
    if (sc === "training_clause" && at === "new_subprocessor") return {to: sc, plan: A.sims[sc]};
    if (sc === "undo" && !clean) return {to: "undo", plan: A.sims.undo};
    if (sc === "training_clause" && clean)
      return {error: "In this recorded run the AI-training clause changed after the new sub-processor. Run \"Tinybird adds a sub-processor\" first."};
    return {to: at, plan: same};
  }
  function startJob(A, kind, sc) {
    if (m.current && m.jobs[m.current].status === "running") return {status: 409, data: {error: "busy"}};
    const n = next(A, kind, sc);
    if (n.error) return {status: 400, data: {error: n.error}};
    const id = "rec" + m.nextId++;
    m.jobs[id] = {id, kind, t0: Date.now(), plan: n.plan, to: n.to, status: "running"};
    m.current = id;
    return {status: 200, data: {job: id}};
  }
  async function startLive(url) {
    if (m.current && m.jobs[m.current].status === "running") return {status: 409, data: {error: "busy"}};
    let r, d = {};
    try { r = await fetch(LIVE + "/check", {method: "POST", headers: {"Content-Type": "application/json"}, body: JSON.stringify({url})}); d = await r.json(); }
    catch { return {status: 502, data: {error: "Can't reach the live checker right now. Try our demo company, trust.nightswatch-inc.example."}}; }
    if (!r.ok || !d.id) return {status: r.status >= 400 ? r.status : 502, data: {error: d.error || "Could not start the check."}};
    const id = "live" + m.nextId++;
    m.jobs[id] = {id, kind: "onboard", live: d.id, status: "running", steps: [], at: 0, error: null};
    m.current = id;
    return {status: 200, data: {job: id}};
  }
  async function liveJob(j) {
    if (Date.now() - j.at > 1500 && j.status === "running") {  // the page polls every 0.6 s; the Worker needs less
      j.at = Date.now();
      try {
        const d = await (await fetch(LIVE + "/check/" + j.live, {cache: "no-store"})).json();
        j.steps = d.steps || j.steps; j.error = d.error || null;
        if (d.status === "done" && d.result) { j.status = "done"; m.live = d.result; m.stage = "live"; }
        else if (d.status === "failed") j.status = "failed";
      } catch { /* keep polling */ }
    }
    return {status: 200, data: {id: j.id, kind: "onboard", status: j.status, steps: j.steps, error: j.error}};
  }
  async function jobView(id) {
    const j = m.jobs[id]; if (!j) return {status: 404, data: {error: "not found"}};
    if (j.live) return liveJob(j);
    const n = Math.floor((Date.now() - j.t0) / (reduced() ? 1 : 850));
    const steps = j.plan.slice(0, n + 1).map(([text, detail], i) => ({text, state: i < n ? "done" : "active", detail: i < n ? detail : ""}));
    if (n >= j.plan.length && j.status === "running") { j.status = "done"; m.stage = j.to; }
    return {status: 200, data: {id, kind: j.kind, status: j.status, steps, error: null}};
  }
  return async (method, path, body) => {
    const A = await rec;
    await new Promise(r => setTimeout(r, 80));
    if (path === "/api/overview") return {status: 200, data: overview(A)};
    if (path === "/api/onboard") {
      let host = ""; try { host = new URL(body.url).hostname.toLowerCase().replace(/^www\./, ""); } catch {}
      return host === demoHost ? startJob(A, "onboard") : startLive(body.url);
    }
    if (path === "/api/chain") return {status: 200, data: {}};
    if (path === "/api/simulate") return startJob(A, "simulate", body.scenario);
    const jm = path.match(/^\/api\/job\/(.+)$/); if (jm) return await jobView(decodeURIComponent(jm[1]));
    return {status: 404, data: {error: "not found"}};
  };
}
"""


def build(s: str) -> str:
    def rep(old: str, new: str) -> None:
        nonlocal s
        assert s.count(old) == 1, f"anchor not found once in app.html: {old[:80]!r}"
        s = s.replace(old, new)

    rep('const MOCK = params.has("mock") && params.get("mock") !== "0";', "const MOCK = true;  // public demo: always the recording")
    a, b = s.index("function makeMock() {"), s.index("const mockApi = MOCK ? makeMock() : null;")
    s = s[:a] + MOCK.replace("__SITE__", SITE).replace("__LIVE__", LIVE) + s[b:]
    rep('n.textContent = "mock data";',
        'n.innerHTML = \'Demo company: a recorded run · any other company: checked live · <a href="guided.html" style="color:inherit">detailed view</a>\';')
    # live results: simulations need lane B's server, so the panel only shows for the recorded demo company
    rep('<section class="block" aria-labelledby="sim-h">',
        '<section class="block" aria-labelledby="sim-h" ${S.ov && S.ov.real ? \'style="display:none"\' : ""}>')
    # "About" is the landing page, which on nightswatch.app sits next to this file
    rep('<a class="about" href="/about/"', '<a class="about" href="./"')
    # the replay offers the changes the recording has; "moves country" and "a company you choose" need the live
    # service (they act on the site the user entered), so they stay on the stage laptop
    a = s.index('const SCENARIOS = [')
    b = s.index('];', a) + 2
    s = s[:a] + '''const SCENARIOS = [
  {id: "new_subprocessor", label: "Adds a new sub-processor (DataHarvest Ltd)"},
  {id: "training_clause", label: "Changes its AI-training clause"},
];''' + s[b:]
    # the "New · Now reads real companies' sub-processor lists" pill: a replay reads nothing live
    a = s.index('<div class="n-pill">')
    s = s[:a].rstrip(" ") + s[s.index("</div>", a) + len("</div>\n"):]
    # rotating industry word + caret: the page's sky blue, deep enough to read (gold was under 2:1 on the sky)
    rep('.n-word{color:#d9a93a;', '.n-word{color:#2f6fae;')
    rep('.n-caret{display:inline-block;width:3px;height:.8em;margin-left:4px;background:#d9a93a;',
        '.n-caret{display:inline-block;width:3px;height:.8em;margin-left:4px;background:#2f6fae;')
    # the recording only changed Tinybird, so that is the one vendor the replay can simulate
    a = s.index('<select class="input sim-vendor" id="sim-vendor">') + len('<select class="input sim-vendor" id="sim-vendor">')
    s = s[:a] + '<option value="tinybird" selected>Tinybird</option>' + s[s.index("</select>", a):]
    assert "Example Email Delivery" not in s and "fetch(path" in s
    return s


if __name__ == "__main__":
    (WEB / "demo.html").write_text(build(APP.read_text()))
    print("wrote web/demo.html from", APP.relative_to(WEB.parent))
