"""Build web/guided.html from web/console.html: same page, but it replays web/demo.json instead of calling the stage
console's /api/state and /api/action. Re-run after console.html changes:

    python3 web/build_demo.py

Each edit asserts its anchor text exists, so a console.html change that moves one fails loudly instead of silently.
"""

from pathlib import Path

WEB = Path(__file__).parent

REPLAY = r"""/* ---------- replay ---------- */
// REC.states[0] is the state before step 1; REC.states[i+1] and REC.steps[i] are what step i's check produced.
let REC=null,at=0;
const wait=ms=>new Promise(r=>setTimeout(r,reduce?0:ms));
function summary(st){
  const t=st.seconds<0.1?'under 0.1':st.seconds;
  if(!st.alerts.length)return `<span class="ok">No alert.</span> Check took ${t} s.`;
  return st.alerts.map(a=>`<span class="${a.kind==='violation'?'bad':'ok'}">${a.kind==='violation'?'Violation':'Resolved'} ${esc(a.rule)}</span> ${esc(cut(a.title,70))}`).join('<br>')+`<br>Check took ${t} s.`;
}
function lock(on){running=on;radar.busy(on);document.body.classList.toggle('busy',on);buttons()}
function buttons(){document.querySelectorAll('.st').forEach((b,i)=>b.disabled=running||i!==at);$('check').disabled=running||at===0}
function show(i){
  S=Object.assign({},REC.states[i]);
  if(changed('v',S.vendors))vendors(S.vendors||[]);
  happened();chart(S.series||{});nums(REC.proof);
  $('at').textContent=S.at;first=false;
}
async function step(card,i){
  if(running||i!==at)return;lock(true);
  const res=card.querySelector('.res'),t0=Date.now();let phase='Editing Tinybird’s demo mirror…';
  card.className='st running';
  const tickr=setInterval(()=>{res.textContent=`${phase} ${Math.round((Date.now()-t0)/1000)} s`},250);
  await wait(900);phase='Night’s Watch is checking Tinybird…';
  // Paced like the real check (capped so nobody waits long); the real time is in the result line.
  await wait(Math.min(4000,1200+REC.steps[i].seconds*250));
  clearInterval(tickr);
  card.className='st done';res.innerHTML=summary(REC.steps[i]);
  at=i+1;show(at);lock(false);
}
function restart(){
  if(running)return;at=0;seen.clear();
  document.querySelectorAll('.st').forEach(b=>{b.className='st';b.querySelector('.res').textContent=''});
  show(0);buttons();
}
document.querySelectorAll('.st').forEach(b=>b.onclick=()=>step(b,+b.dataset.i));
$('check').onclick=restart;
(async()=>{
  try{REC=await (await fetch('demo.json')).json();show(0);buttons()}
  catch(e){$('at').textContent='could not load the recording';$('hr').classList.add('off')}
})();
"""


def build(s: str) -> str:
    def rep(old: str, new: str) -> None:
        nonlocal s
        assert s.count(old) == 1, f"anchor not found once in console.html: {old[:80]!r}"
        s = s.replace(old, new)

    rep("<title>Night's Watch · Live</title>", "<title>Night's Watch · Demo</title>")
    a, b = s.index("/* Stage console, lane C."), s.index("*/", s.index("/* Stage console, lane C.")) + 2
    s = s[:a] + """/* Public demo, lane C. GENERATED by web/build_demo.py from web/console.html: edit those, not this file.
   Replays demo.json (the stage console's /api/state after each check) instead of calling the live API.
   Regenerate the recording with: NW_TABLE_SUFFIX=_e2e uv run python web/export_demo.py */""" + s[b:]
    # header: say it is a recording, link home
    rep('<span class="wordmark">', '<a class="wordmark" href="./">')
    rep('Night\'s Watch</span>\n  <span class="tag">Live demo</span>',
        'Night\'s Watch</a>\n  <span class="tag">Recorded demo</span>')
    rep('<span id="at">connecting…</span><span>·</span><span>tables <b>__SUFFIX__</b></span>',
        '<span id="at">loading…</span><span>·</span><span>replay of a real run</span>')
    rep('.hr b{font-weight:500;color:var(--amber)}',
        '.hr b{font-weight:500;color:var(--amber)}\na.wordmark{color:inherit;text-decoration:none}\n'
        '.intro{margin:0 0 12px;color:var(--ink-2);font-size:13.5px;line-height:1.5}')
    # controls: intro line, "Start over" instead of Check now / View log, no Recompute
    rep('<div class="eyebrow">Run the demo</div>',
        '<div class="eyebrow">Run the demo</div>\n    <p class="intro">A replay of one real run on our demo mirror of '
        'Tinybird\'s pages. Every alert, lookup and memory edit below came from the agent. Click the steps in order.</p>')
    rep('<button class="btn" id="check" type="button">Check now</button>\n      '
        '<button class="link" id="showlog" type="button" disabled>View log</button>',
        '<button class="btn" id="check" type="button">Start over</button>')
    rep('<span class="r"><button class="link" id="proof" type="button">Recompute</button></span>',
        '<span class="r">offline simulation</span>')
    a = s.index('<div class="modal" id="modal"')
    s = s[:a] + s[s.index("</div>\n</div>\n", a) + len("</div>\n</div>\n"):]
    # evidence: the tunnel that served the mirror is gone, so show the page path without a link
    rep("""let proof='';try{proof=`<a href="${esc(a.evidence_url)}" target="_blank" rel="noopener">${esc(new URL(a.evidence_url).pathname)} ↗</a>`}catch(e){}""",
        """let proof='';try{proof=`${esc(new URL(a.evidence_url).pathname)} <span class="empty">(demo mirror, recorded)</span>`}catch(e){}""")
    rep("<dd>${vs.length} vendors and their sub-processors. Run a step to make a change.</dd>",
        "<dd>${vs.length} vendors and their sub-processors. Click step 1 to make a change.</dd>")
    rep("Not computed yet. Press Recompute (about 10 s, offline).", "Not recorded.")
    # actions + polling -> replay
    a, b = s.index("/* ---------- actions ---------- */"), s.index("let rz;addEventListener")
    s = s[:a] + REPLAY + s[b:]
    rep("poll();setInterval(poll,2000);\n", "")
    for gone in ("fetch('/api", "poll(", "showlog", "logText+="):
        assert gone not in s, f"live-console code left in demo: {gone}"
    return s


if __name__ == "__main__":
    (WEB / "guided.html").write_text(build((WEB / "console.html").read_text()))
    print("wrote web/guided.html")
